import type { BookingRecord, ReconcileResult, SupplierStatement } from './reconcile.js';

export const SAMPLE_STATEMENTS: SupplierStatement[] = [
  {
    id: 'singita-q3-2026',
    supplier: 'Singita',
    period: 'Q3 2026',
    currency: 'USD',
    lines: [
      {
        ref: 'SNG-260701',
        client: 'Ainsley Mercer',
        travelDates: '12 Jul 2026 - 19 Jul 2026',
        grossFare: 48000,
        commissionRatePaid: 0.12,
        commissionPaid: 5760,
      },
      {
        ref: 'SNG-260715',
        client: 'Hartwell Family',
        travelDates: '22 Jul 2026 - 29 Jul 2026',
        grossFare: 73500,
        commissionRatePaid: 0.12,
        commissionPaid: 8820,
      },
      {
        ref: 'SNG-260811',
        client: 'Priya Shah',
        travelDates: '14 Aug 2026 - 21 Aug 2026',
        grossFare: 56200,
        commissionRatePaid: 0.1,
        commissionPaid: 5620,
      },
      {
        ref: 'SNG-260905',
        client: 'Emilia Laurent',
        travelDates: '6 Sep 2026 - 13 Sep 2026',
        grossFare: 64100,
        commissionRatePaid: 0.12,
        commissionPaid: 7692,
      },
      {
        ref: 'SNG-260918',
        client: 'Nakamura Party',
        travelDates: '21 Sep 2026 - 27 Sep 2026',
        grossFare: 42500,
        commissionRatePaid: 0.12,
        commissionPaid: 5100,
      },
    ],
  },
  {
    id: 'explora-august-2026',
    supplier: 'Explora Journeys',
    period: 'August 2026',
    currency: 'USD',
    lines: [
      {
        ref: 'EXP-260801',
        client: 'Alden Grant',
        travelDates: '2 Aug 2026 - 12 Aug 2026',
        grossFare: 36400,
        commissionRatePaid: 0.14,
        commissionPaid: 5096,
      },
      {
        ref: 'EXP-260806',
        client: 'Sofia Bennett',
        travelDates: '6 Aug 2026 - 16 Aug 2026',
        grossFare: 42100,
        commissionRatePaid: 0.14,
        commissionPaid: 5894,
      },
      {
        ref: 'EXP-260812',
        client: 'Reyes Family',
        travelDates: '12 Aug 2026 - 22 Aug 2026',
        grossFare: 58800,
        commissionRatePaid: 0.12,
        commissionPaid: 7056,
      },
      {
        ref: 'EXP-260817',
        client: 'Oliver Black',
        travelDates: '17 Aug 2026 - 24 Aug 2026',
        grossFare: 6000,
        commissionRatePaid: 0.14,
        commissionPaid: 840,
      },
      {
        ref: 'EXP-260819',
        client: 'Morgan Lee',
        travelDates: '19 Aug 2026 - 29 Aug 2026',
        grossFare: 30900,
        commissionRatePaid: 0.14,
        commissionPaid: 4326,
      },
      {
        ref: 'EXP-260824',
        client: 'Chen Patel',
        travelDates: '24 Aug 2026 - 3 Sep 2026',
        grossFare: 47600,
        commissionRatePaid: 0.14,
        commissionPaid: 6664,
      },
    ],
  },
  {
    id: 'four-seasons-august-2026',
    supplier: 'Four Seasons',
    period: 'August 2026',
    currency: 'USD',
    lines: [
      {
        ref: 'FS-260803',
        client: 'Charlotte Vale',
        travelDates: '3 Aug 2026 - 10 Aug 2026',
        grossFare: 52800,
        commissionRatePaid: 0.1,
        commissionPaid: 5280,
      },
      {
        ref: 'FS-260807',
        client: 'Hayes Family',
        travelDates: '7 Aug 2026 - 15 Aug 2026',
        grossFare: 81250,
        commissionRatePaid: 0.1,
        commissionPaid: 8125,
      },
      {
        ref: 'FS-260812',
        client: 'Isabella Noor',
        travelDates: '12 Aug 2026 - 18 Aug 2026',
        grossFare: 44700,
        commissionRatePaid: 0.1,
        commissionPaid: 4467,
      },
      {
        ref: 'FS-260816',
        client: 'Park & Ellis',
        travelDates: '16 Aug 2026 - 24 Aug 2026',
        grossFare: 63900,
        commissionRatePaid: 0.1,
        commissionPaid: 6390,
      },
      {
        ref: 'FS-260822',
        client: 'Matteo Rinaldi',
        travelDates: '22 Aug 2026 - 27 Aug 2026',
        grossFare: 38500,
        commissionRatePaid: 0.1,
        commissionPaid: 3850,
      },
      {
        ref: 'FS-260829',
        client: 'Spencer Gray',
        travelDates: '29 Aug 2026 - 5 Sep 2026',
        grossFare: 71900,
        commissionRatePaid: 0.1,
        commissionPaid: 7190,
      },
    ],
  },
];

export const TRAMS_BOOKING_LEDGER: BookingRecord[] = [
  {
    ref: 'SNG-260701',
    client: 'Ainsley Mercer',
    supplier: 'Singita',
    travelDates: '12 Jul 2026 - 19 Jul 2026',
    grossFare: 48000,
    contractedRate: 0.12,
    expectedCommission: 5760,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'SNG-260715',
    client: 'Hartwell Family',
    supplier: 'Singita',
    travelDates: '22 Jul 2026 - 29 Jul 2026',
    grossFare: 73500,
    contractedRate: 0.12,
    expectedCommission: 8820,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'SNG-260811',
    client: 'Priya Shah',
    supplier: 'Singita',
    travelDates: '14 Aug 2026 - 21 Aug 2026',
    grossFare: 56200,
    contractedRate: 0.12,
    expectedCommission: 6744,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'SNG-260823',
    client: 'Bennett & Cole',
    supplier: 'Singita',
    travelDates: '25 Aug 2026 - 1 Sep 2026',
    grossFare: 38800,
    contractedRate: 0.12,
    expectedCommission: 4656,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'SNG-260905',
    client: 'Emilia Laurent',
    supplier: 'Singita',
    travelDates: '6 Sep 2026 - 13 Sep 2026',
    grossFare: 64100,
    contractedRate: 0.12,
    expectedCommission: 7692,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'SNG-260918',
    client: 'Nakamura Party',
    supplier: 'Singita',
    travelDates: '21 Sep 2026 - 27 Sep 2026',
    grossFare: 42500,
    contractedRate: 0.12,
    expectedCommission: 5100,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'EXP-260801',
    client: 'Alden Grant',
    supplier: 'Explora Journeys',
    travelDates: '2 Aug 2026 - 12 Aug 2026',
    grossFare: 36400,
    contractedRate: 0.14,
    expectedCommission: 5096,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'EXP-260806',
    client: 'Sofia Bennett',
    supplier: 'Explora Journeys',
    travelDates: '6 Aug 2026 - 16 Aug 2026',
    grossFare: 42100,
    contractedRate: 0.14,
    expectedCommission: 5894,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'EXP-260812',
    client: 'Reyes Family',
    supplier: 'Explora Journeys',
    travelDates: '12 Aug 2026 - 22 Aug 2026',
    grossFare: 58800,
    contractedRate: 0.14,
    expectedCommission: 8232,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'EXP-260819',
    client: 'Morgan Lee',
    supplier: 'Explora Journeys',
    travelDates: '19 Aug 2026 - 29 Aug 2026',
    grossFare: 30900,
    contractedRate: 0.14,
    expectedCommission: 4326,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'EXP-260824',
    client: 'Chen Patel',
    supplier: 'Explora Journeys',
    travelDates: '24 Aug 2026 - 3 Sep 2026',
    grossFare: 47600,
    contractedRate: 0.14,
    expectedCommission: 6664,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'FS-260803',
    client: 'Charlotte Vale',
    supplier: 'Four Seasons',
    travelDates: '3 Aug 2026 - 10 Aug 2026',
    grossFare: 52800,
    contractedRate: 0.1,
    expectedCommission: 5280,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'FS-260807',
    client: 'Hayes Family',
    supplier: 'Four Seasons',
    travelDates: '7 Aug 2026 - 15 Aug 2026',
    grossFare: 81250,
    contractedRate: 0.1,
    expectedCommission: 8125,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'FS-260812',
    client: 'Isabella Noor',
    supplier: 'Four Seasons',
    travelDates: '12 Aug 2026 - 18 Aug 2026',
    grossFare: 44700,
    contractedRate: 0.1,
    expectedCommission: 4470,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'FS-260816',
    client: 'Park & Ellis',
    supplier: 'Four Seasons',
    travelDates: '16 Aug 2026 - 24 Aug 2026',
    grossFare: 63900,
    contractedRate: 0.1,
    expectedCommission: 6390,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'FS-260822',
    client: 'Matteo Rinaldi',
    supplier: 'Four Seasons',
    travelDates: '22 Aug 2026 - 27 Aug 2026',
    grossFare: 38500,
    contractedRate: 0.1,
    expectedCommission: 3850,
    status: 'Confirmed in Trams',
  },
  {
    ref: 'FS-260829',
    client: 'Spencer Gray',
    supplier: 'Four Seasons',
    travelDates: '29 Aug 2026 - 5 Sep 2026',
    grossFare: 71900,
    contractedRate: 0.1,
    expectedCommission: 7190,
    status: 'Confirmed in Trams',
  },
];

export const SAMPLE_RESULTS: Record<string, ReconcileResult> = {
  'singita-q3-2026': {
    summary:
      'Singita Q3 reconciles to four matched bookings and two exceptions: one August booking was paid at 10% against a 12% contract, and one confirmed Trams booking is absent from the statement.',
    lines: [
      {
        ref: 'SNG-260701',
        client: 'Ainsley Mercer',
        outcome: 'matched',
        expected: 5760,
        paid: 5760,
        variance: 0,
        note: 'Statement amount matches the 12% contracted commission.',
      },
      {
        ref: 'SNG-260715',
        client: 'Hartwell Family',
        outcome: 'matched',
        expected: 8820,
        paid: 8820,
        variance: 0,
        note: 'Statement amount matches the Trams booking and contracted rate.',
      },
      {
        ref: 'SNG-260811',
        client: 'Priya Shah',
        outcome: 'short_paid',
        expected: 6744,
        paid: 5620,
        variance: 1124,
        note: 'Statement paid 10%; Trams contract expects 12%.',
      },
      {
        ref: 'SNG-260905',
        client: 'Emilia Laurent',
        outcome: 'matched',
        expected: 7692,
        paid: 7692,
        variance: 0,
        note: 'Statement amount matches the Trams booking.',
      },
      {
        ref: 'SNG-260918',
        client: 'Nakamura Party',
        outcome: 'matched',
        expected: 5100,
        paid: 5100,
        variance: 0,
        note: 'Statement amount matches the Trams booking.',
      },
      {
        ref: 'SNG-260823',
        client: 'Bennett & Cole',
        outcome: 'missing_from_statement',
        expected: 4656,
        paid: 0,
        variance: 4656,
        note: 'Confirmed Trams booking does not appear on the supplier statement.',
      },
    ],
    totals: {
      expected: 38772,
      paid: 32992,
      variance: 5780,
      matchedCount: 4,
      exceptionCount: 2,
    },
    disputeEmail: {
      subject: 'Singita Q3 2026 commission reconciliation',
      body: `Dear Singita Finance Team,

Thank you for sending the Q3 2026 commission statement. We have reconciled it against our Trams ledger and found two items that appear to need review.

SNG-260811 for Priya Shah was paid at 10%, or $5,620, against our contracted 12% commission. The expected commission is $6,744, leaving a variance of $1,124.

SNG-260823 for Bennett & Cole appears in Trams as a confirmed booking for 25 August 2026 to 1 September 2026, with expected commission of $4,656, but we do not see it on the statement.

Could you please review these references and arrange remittance of the $5,780 variance if your records agree. Julie Boucher, our CFO, is copied in our internal review notes and will approve the queue before anything is sent from our side.

With thanks,
Tully Luxury Travel · Finance`,
    },
    confidence: 'high',
  },
  'explora-august-2026': {
    summary:
      'Explora Journeys August shows four matched bookings and two exceptions: one booking was paid at 12% against a 14% contract, while one cancelled reference appears on the statement without an active Trams ledger booking.',
    lines: [
      {
        ref: 'EXP-260801',
        client: 'Alden Grant',
        outcome: 'matched',
        expected: 5096,
        paid: 5096,
        variance: 0,
        note: 'Statement amount matches the 14% contracted commission.',
      },
      {
        ref: 'EXP-260806',
        client: 'Sofia Bennett',
        outcome: 'matched',
        expected: 5894,
        paid: 5894,
        variance: 0,
        note: 'Statement amount matches the Trams booking.',
      },
      {
        ref: 'EXP-260812',
        client: 'Reyes Family',
        outcome: 'rate_mismatch',
        expected: 8232,
        paid: 7056,
        variance: 1176,
        note: 'Statement applies 12%; contracted commission in Trams is 14%.',
      },
      {
        ref: 'EXP-260817',
        client: 'Oliver Black',
        outcome: 'not_in_ledger',
        expected: 0,
        paid: 840,
        variance: -840,
        note: 'No active Trams booking is present; operations marked this reference cancelled.',
      },
      {
        ref: 'EXP-260819',
        client: 'Morgan Lee',
        outcome: 'matched',
        expected: 4326,
        paid: 4326,
        variance: 0,
        note: 'Statement amount matches the Trams booking.',
      },
      {
        ref: 'EXP-260824',
        client: 'Chen Patel',
        outcome: 'matched',
        expected: 6664,
        paid: 6664,
        variance: 0,
        note: 'Statement amount matches the Trams booking.',
      },
    ],
    totals: {
      expected: 30212,
      paid: 29876,
      variance: 336,
      matchedCount: 4,
      exceptionCount: 2,
    },
    disputeEmail: {
      subject: 'Explora Journeys August 2026 commission reconciliation',
      body: `Dear Explora Journeys Finance Team,

Thank you for the August 2026 commission statement. We have completed our reconciliation against Trams and found two references that we would be grateful for you to review.

EXP-260812 for the Reyes Family appears to have been paid at 12%, or $7,056. Our contracted rate is 14%, with expected commission of $8,232, creating a $1,176 shortfall.

EXP-260817 for Oliver Black does not appear as an active booking in our Trams ledger and is noted internally as cancelled. The statement includes $840 for that reference. If that credit should be offset against the shortfall, the net variance due to Tully is $336.

Could you please confirm the treatment of EXP-260817 and arrange remittance of the net variance once confirmed. Julie Boucher, our CFO, is copied in our internal review notes and will approve the queue before anything is sent from our side.

With thanks,
Tully Luxury Travel · Finance`,
    },
    confidence: 'medium',
  },
  'four-seasons-august-2026': {
    summary:
      'Four Seasons August reconciles cleanly. All six bookings match the Trams ledger, with one $3 rounding difference kept inside the $5 tolerance.',
    lines: [
      {
        ref: 'FS-260803',
        client: 'Charlotte Vale',
        outcome: 'matched',
        expected: 5280,
        paid: 5280,
        variance: 0,
        note: 'Statement amount matches the 10% contracted commission.',
      },
      {
        ref: 'FS-260807',
        client: 'Hayes Family',
        outcome: 'matched',
        expected: 8125,
        paid: 8125,
        variance: 0,
        note: 'Statement amount matches the Trams booking.',
      },
      {
        ref: 'FS-260812',
        client: 'Isabella Noor',
        outcome: 'matched',
        expected: 4470,
        paid: 4467,
        variance: 3,
        note: 'Rounding variance is under the $5 tolerance and is treated as matched.',
      },
      {
        ref: 'FS-260816',
        client: 'Park & Ellis',
        outcome: 'matched',
        expected: 6390,
        paid: 6390,
        variance: 0,
        note: 'Statement amount matches the Trams booking.',
      },
      {
        ref: 'FS-260822',
        client: 'Matteo Rinaldi',
        outcome: 'matched',
        expected: 3850,
        paid: 3850,
        variance: 0,
        note: 'Statement amount matches the Trams booking.',
      },
      {
        ref: 'FS-260829',
        client: 'Spencer Gray',
        outcome: 'matched',
        expected: 7190,
        paid: 7190,
        variance: 0,
        note: 'Statement amount matches the Trams booking.',
      },
    ],
    totals: {
      expected: 35305,
      paid: 35302,
      variance: 3,
      matchedCount: 6,
      exceptionCount: 0,
    },
    disputeEmail: {
      subject: 'Four Seasons August 2026 commission reconciliation',
      body: `Dear Four Seasons Finance Team,

Thank you for sending the August 2026 commission statement. We have reconciled the statement against our Trams ledger and all six references match our records.

The only difference is FS-260812 for Isabella Noor, where our expected commission is $4,470 and the statement reflects $4,467. We are treating the $3 difference as rounding within tolerance, so no remittance request is needed.

We will keep this note with the finance file for Julie Boucher's review.

With thanks,
Tully Luxury Travel · Finance`,
    },
    confidence: 'high',
  },
};

export function findSampleStatement(statementId: string): SupplierStatement | undefined {
  return SAMPLE_STATEMENTS.find((statement) => statement.id === statementId);
}

export function ledgerForSupplier(supplier: string): BookingRecord[] {
  return TRAMS_BOOKING_LEDGER.filter((record) => record.supplier === supplier);
}
